steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/big-data-project-380714/front:0.1', '.']
options:
  logging: CLOUD_LOGGING_ONLY
images:
- 'gcr.io/big-data-project-380714/front:0.1'  