# Generated by Django 4.1.7 on 2023-05-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900, null=True)),
                ('theme_id', models.IntegerField(db_column='themeId', null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_column='createdAt', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('question_id', models.IntegerField(db_column='questionId', null=True)),
                ('id_user_response', models.IntegerField(db_column='idUserResponse', null=True)),
                ('created_at', models.DateTimeField(db_column='CreatedAt', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=100, null=True)),
                ('is_true', models.IntegerField(db_column='isTrue', null=True)),
                ('id_question', models.IntegerField(db_column='idQuestion', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
