# Generated by Django 4.1.7 on 2023-05-04 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='id_user_response',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='play.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='response_id',
            field=models.ForeignKey(db_column='idUserResponse', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='play.response'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='theme_id',
            field=models.ForeignKey(db_column='themeId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='play.theme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_id',
            field=models.ForeignKey(db_column='questionId', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='play.question'),
            preserve_default=False,
        ),
    ]
