# Generated by Django 4.1.7 on 2023-05-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_remove_question_type_remove_quiz_id_user_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='id_question',
            field=models.ForeignKey(db_column='idQuestion', on_delete=django.db.models.deletion.DO_NOTHING, to='play.question'),
        ),
    ]
