# Generated by Django 4.1.7 on 2023-04-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='play.quiz'),
            preserve_default=False,
        ),
    ]
