# Generated by Django 4.1.7 on 2023-05-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_alter_response_id_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='is_true',
            field=models.BooleanField(db_column='isTrue', null=True),
        ),
    ]
