# Generated by Django 4.1.7 on 2023-05-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0004_alter_response_is_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
