# Generated by Django 4.1.7 on 2023-05-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_quiz_quiz_hash'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='quiz',
            table='quizz',
        ),
        migrations.AlterModelTable(
            name='response',
            table='reponse',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='theme',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
