# Generated by Django 4.1.7 on 2023-04-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_quiz_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_answer',
            field=models.BooleanField(default=False),
        ),
    ]
