# Generated by Django 4.1.7 on 2023-05-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_alter_question_table_alter_quiz_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='response',
            table='response',
        ),
    ]
