# Generated by Django 4.1.7 on 2023-04-18 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_answer_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
