# Generated by Django 4.1.7 on 2023-05-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_alter_response_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='response',
            table=None,
        ),
    ]
